### ISSUE TITLE
503 after enabling Profiler

### ISSUE THREAD

**Issue by ins4n333** [Microsoft/ApplicationInsights-Profiler-AspNetCore#10]
Hi!
I have a small .net core app. This app is hosted as a docker container in Kubernetes. When I enable Application Insights Profiller  then all request to this application falls in 503 error (Bad Gateway)
I tryed to enable profiling using both methods  "ENV ASPNETCORE_HOSTINGSTARTUPASSEMBLIES Microsoft.ApplicationInsights.Profiler.AspNetCore" and "services.AddServiceProfiler();"
But  the error  still remained. How can I investigate this problem?

I see in application logs only:
{"Timestamp":"2018-05-03T12:08:38.1261884+00:00","Level":"Information","MessageTemplate":"Service Profiler session started.","SourceContext":"ServiceProfiler.EventPipe.Client.Schedules.TraceSchedule","ConversationId":"(none)","ProfilingContext":"(none)"}

**Comment by xiaomi7732** [comment]
@ins4n333 Thank you for using Service Profiler. I am sorry to hear that it doesn't work for you and also for the delayed reply. Kubernetes hosted container should be working.

By the description, the app is working properly without enable Service Profiler but returns 503(Server Internal Error) when has Service Profiler Enabled, is that correct?

You said you are using both environment variable and calling services.AddServiceProfiler(). I am not sure if you are using both at the same time or you mean you tried both method. Because of bug #6 , you can use either but please do NOT use both at the same time. (Well, until the next release that contains the fix.)

Secondly, please set the log level to `Debug` to see if you could see some more traces:
```json
    "LogLevel": {
      "Default": "Warning",
      "ServiceProfiler":"Debug"
    }
```
Please use gather the following details:
1. kubectl logs <pod>
2. kubectl describe <pod>

Please paste the result here, I will take a look.

**Comment by ins4n333** [comment]
Hi @xiaomi7732 ! I have already analazyed this problem. It turns out when I deploy application with enabled profiler my pods fall in OOM... It depends on the fact that I had had pods which are limited in CPU and MEMORY.  But the profiler itself requires some amount of memory for correct work. After that I increased memory limit of pod my application started fine and profiler was able to collect some traces. But when I tryed to open these traces using portal I received "Issue loading trace with correlation id: xnlayhmq".
Does this fact correlated with that I use .NETCORE 2.0 runtime (not 2.1)?

**Comment by xiaomi7732** [comment]
@ins4n333 Thanks for looking into the issue. Really appreciate it. **With the correlation id** you provided, I checked the telemetry on our end and it is the typical CLR 2.0 run-time failure.
====
I just want to mention here is that there is a new issue in our back-end to analyze CLR 2.1 traces because of a recent CLR change. The issue is tracked by #11 . Please hold it a bit if you want to try it on CLR 2.1.

**Comment by ins4n333** [comment]
@xiaomi7732 Thank you! I belive that AI profiler will be very useful tecknology for diagnostic perfmonce problems. Existense Linux tools for dotnet profiling (such as perf) are not very convenient..

**Comment by xiaomi7732** [comment]
Very pleased to hear that :-) Thanks again for using the profiler and give us the feedback.
I'll lock this conversation for references.

Feel free to open up new issues at anytime if there's more info.
