### ISSUE TITLE
All Requests Have Broken Stacks in Hot Path

### ISSUE THREAD

**Issue by ericmattingly** [microsoft/ApplicationInsights-Profiler-AspNetCore#132]
I have the 2.2.0-beta6 profiler enabled on a .NET Core 3.1 service running in a Linux Alpine container in AKS.

Every profile tree seems to have broken stacks.  What's my next steps for troubleshooting?

![image](https://user-images.githubusercontent.com/10789017/107174451-1f30ff80-697f-11eb-90d1-f858e8a657b7.png)

**Comment by xiaomi7732** [comment]
Talked with @ericmattingly offline. I have submitted the problem upstream team for further analysis. Tag @sywhang.

**Comment by xiaomi7732** [comment]
@ericmattingly Thanks for the report. @sywhang found the issue. It is a bug in our backend service. I will issue an fix there. It will take a couple of weeks before it hits the service. At the same time, please ignore the BROKEN for now. Other than showing the broken node, the call tree should still be trustworthy.

Thanks @ericmattingly for reporting the issue & @sywhang for point out where the issue is.

I'll keep this issue open until our backend service is deployed with the fix.

**Comment by xiaomi7732** [comment]
The deployment for this fix has started. It will take about 1 week for it to reach global if everything goes smoothly.

**Comment by xiaomi7732** [comment]
The change has been deployed. Feel free to open new issues if there's anything else.
