### ISSUE TITLE
Need a configuration that disables regular profiling but keeps triggered ones

### ISSUE THREAD

**Issue by AdrenalineHc** [microsoft/ApplicationInsights-Profiler-AspNetCore#148]
for now the profiler regular run is every 1 hour, but I am only interested for special scenarios, need a button to do that, especially for web app's codeless agent, thx

**Comment by xiaomi7732** [comment]
Hi @AdrenalineHc, the codeless agent already supports that scenario:

![image](https://user-images.githubusercontent.com/3674549/139507213-c055541c-3652-40eb-abb1-598017f86e02.png)

Does that addresses your issue?

**Comment by TeplrGuy** [comment]
@xiaomi7732 any reason why you say this option is only available to codeless agent config? Does this mean on a Linux hosted .NET core application sample cannot be turned off from the portal?

**Comment by xiaomi7732** [comment]
@TeplrGuy Thanks for bring this up. It was the case. However, due to a recent effort by @JacobBovee , Linux Profiler agent now supports using settings from the portal too. Refer to #158 for more details. You will need to use the latest NuGet package to try it out:
<https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.4.0-beta1>

Feel free to open new issue if you have further questions.
