### ISSUE TITLE
IsDisabled: true breaks routing

### ISSUE THREAD

**Issue by wow-anton** [microsoft/ApplicationInsights-Profiler-AspNetCore#85]
When `IsDisabled=true` all controller action return 404.
When `IsDisabled=false` controller actions work again.

App is a basic .netcoreapp3.1 bootstrapped with `dotnet new webapi` template and only added `.AddServiceProfiler()`

Version: **2.1.0-beta2** (2.1.0-beta1 works OK)

**Comment by xiaomi7732** [comment]
@wow-anton, thanks for the report. Sounds like a bug. I'll take a look.

**Comment by xiaomi7732** [comment]
@wow-anton Thanks for reporting this issue. The issue is caused by a code bug I introduced recently.

When the profiler is disabled - either by intentionally set `IsDisabled` to true or by other reasons, no iKey is set, for example - it will break the startup of ASP.NET Core app, thus the controllers can't be reached.

I am issuing a quick fix for it and will post a new release ASAP.

**Comment by xiaomi7732** [comment]
Please use [2.1.0-beta3](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta3) instead.
